config/routes.rb
Rails.application.routes.draw do

  devise_for :users


  resources :users, only: [:index, :show] do
    member do
      get :follow
      get :unfollow
      get :followers
      get :following
    end
  end

  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  acts_as_followable
  acts_as_follower


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end


  def follow
    @user = User.find(params[:id])

    current_user.follow(@user)

    redirect_to action: 'show'
  end

  def unfollow

    @user = User.find(params[:id])

    current_user.stop_following(@user)

    redirect_to action: 'show'
  end

  def followers
    @user = User.find(params[:id])

  end

  def following
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FollowOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/nav' %>

    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "FollowOnRails", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-md-auto">


      <% if user_signed_in? %>

      <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete,  class: 'nav-link' %>
      </li>

      <% else %>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %>
      </li>


      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class: 'nav-link' %>
      </li>

      <% end %>





  </div>
</nav>

app/views/users/followers.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-12">


      <div class="card">

        <div class="card-header">
          <%= @user.email %>
        </div>


        <div class="card-content">

          <ul>




          <% @user.followers.each do |u| %>
            <li>
              <%= link_to u.email, user_path(u.id)  %>


            </li>

          <% end %>

            </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/following.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-12">


      <div class="card">

        <div class="card-header">
          <%= @user.email %>
        </div>


        <div class="card-content">

          <ul>




          <% @user.all_following.each do |u| %>
            <li>
              <%= link_to u.email, user_path(u.id)  %>


            </li>

          <% end %>

            </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <% @users.each do |u| %>

      <div class="col-md-4">
        <br>
        <br>
        
        <div class="card">
          <div class="card-header">
            <%= u.email %>
          </div>

          <div class="card-content text-center">

            <%= image_tag('patterns.jpg', width: "100%") %>


            <p class="lead">
              Followers: <%= u.followers_count %>
            </p>


            <%= link_to "View User", user_path(u.id), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>


    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="banner">
</div>

<br>
<br>
<br>

<div class="container">

  <div class="row">


    <div class="col-md-3">

      <h3>
        <%= @user.email %>

      </h3>
      <p class="lead">
        <%= link_to "Followers:", followers_user_path %> <%= @user.followers_count %>
      </p>

      <p class="lead">
        <%= link_to "Following:", following_user_path %> <%= @user.follow_count %>
      </p>

      <% if current_user === @user %>


      <% else %>
        <% if current_user.following?(@user) %>
          <%= link_to "Unfollow", unfollow_user_path, class: 'btn btn-danger' %>

        <% else %>
        <%= link_to "Follow Me", follow_user_path, class: 'btn btn-primary' %>

        <% end %>
      <% end %>



    </div>
  </div>
</div>